config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'

  resources :events
  resources :categories
  resources :clientes

  root 'clientes#index'

  get 'orders' => 'orders#index'
  post 'orders/new/' => 'orders#new_orders'
  get  'orders/show/:id' => 'orders#show'
  get  'orders/all/' => 'orders#getallorders'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :orders, dependent: :destroy
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index

    @search = Cliente.search(params[:q])
    @clientes = @search.result
    @clientes = @clientes.paginate(:per_page => 5, :page => params[:page])

  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:rut, :first_name, :last_name, :address, :region, :city, :postal_code)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Rut" %><br>
    <%= f.text_field :rut ,:class=> 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label "Nombre" %><br>
    <%= f.text_field :first_name ,:class=> 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label "Apellidos" %><br>
    <%= f.text_field :last_name,:class=> 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Dirección" %><br>
    <%= f.text_field :address,:class=> 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Region" %><br>
    <%= f.text_field :region,:class=> 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Ciudad" %><br>
    <%= f.text_field :city,:class=> 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Código Postal" %><br>
    <%= f.text_field :postal_code ,:class=> 'form-control'%>
  </div>
  <%= f.submit 'Guardar Cliente', :class => 'btn btn-success' %>

  <br>
<% end %>

app/views/clientes/edit.html.erb
<h1>
  <i class="fa fa-users"></i>
  Editar Cliente</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Ver', @cliente, :class=> 'btn btn-default'  %> |
<%= link_to 'Volver', clientes_path,:class=> 'btn btn-default'  %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><i class="fa fa-users"></i>
 Clientes
<%= link_to 'Nuevo Cliente', new_cliente_path, :class=> 'btn btn-default text-right' %>
</h1>
<hr>

<div class="panel panel-default">
  <div class="panel-heading">

    <%= search_form_for @search do |f| %>
      <div class="input-group">
          <%= f.text_field :rut_or_first_name_or_last_name_cont, :class=>"form-control", :placeholder=>"Ingrese termino de busqueda y presione ENTER" %>
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    <% end %>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Rut</th>
          <th>Nombre</th>
          <th>Apellidos</th>
          <th>Dirección</th>
          <th>Region</th>
          <th>Ciudad</th>
          <th>Codigo Postal</th>
          <th>Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @clientes.each do |cliente| %>
          <tr>
            <td><%= cliente.rut %></td>
            <td><%= cliente.first_name %></td>
            <td><%= cliente.last_name %></td>
            <td><%= cliente.address %></td>
            <td><%= cliente.region %></td>
            <td><%= cliente.city %></td>
            <td><%= cliente.postal_code %></td>
            <td>
              <div class="btn-group">
                <%= link_to '', cliente , :class =>"btn btn-default btn-sm fa fa-eye" %>
                <%= link_to '', edit_cliente_path(cliente), :class =>"btn btn-warning btn-sm fa fa-pencil"%>
                <%= link_to '', cliente, method: :delete, data: { confirm: 'Estas Seguro?' }, :class =>"btn btn-danger btn-sm fa fa-trash" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @clientes, renderer: BootstrapPagination::Rails %>
    <br>
  </div>
</div>

app/views/clientes/new.html.erb
<h1><i class="fa fa-users"></i>Nuevo Cliente</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Volver', clientes_path,:class=> 'btn btn-default'  %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
  <p>
    <strong>Rut:</strong>
    <%= @cliente.rut %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= @cliente.first_name %>
  </p>

  <p>
    <strong>Apellidos:</strong>
    <%= @cliente.last_name %>
  </p>

  <p>
    <strong>Dirección:</strong>
    <%= @cliente.address %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= @cliente.region %>
  </p>

  <p>
    <strong>Ciudad:</strong>
    <%= @cliente.city %>
  </p>

  <p>
    <strong>Código Postal:</strong>
    <%= @cliente.postal_code %>
  </p>
</div>
<div class="well">
  <%= link_to 'Editar', edit_cliente_path(@cliente), :class=>"btn btn-default" %> |
  <%= link_to 'Volver', clientes_path, :class=>"btn btn-default" %>
</div>