config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'

  resources :events
  resources :categories
  resources :clientes

  root 'clientes#index'

  get 'orders' => 'orders#index'
  post 'orders/new/' => 'orders#new_orders'
  get  'orders/show/:id' => 'orders#show'
  get  'orders/all/' => 'orders#getallorders'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @search = Event.search(params[:q])
    @events = @search.result
    @events = @events.paginate(:per_page => 5, :page => params[:page])
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
    <%= f.submit 'Guardar Evento', :class => "btn btn-success" %>

<% end %>
<br>

app/views/events/edit.html.erb
<h1><i class="fa fa-bullhorn"></i>
 Editar Evento
</h1>

<%= render 'form' %>

<%= link_to 'Ver', @event, :class=> 'btn btn-default' %> |
<%= link_to 'Volver', events_path , :class=> 'btn btn-default'%>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1><i class="fa fa-bullhorn"></i>
 Eventos
 <%= link_to 'Nuevo Evento', new_event_path, :class=> 'btn btn-default text-right' %> <br>
</h1>

<hr>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= search_form_for @search do |f| %>
      <div class="input-group">
        <%= f.text_field :name_cont, :class=>"form-control",:name=>"Search", :placeholder=>"Ingrese termino de busqueda y presione ENTER" %>
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    <% end %>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nombre del Evento</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td>
              <div class="btn-group">
                <%= link_to '', event , :class =>"btn btn-default btn-sm fa fa-eye" %>
                <%= link_to '', edit_event_path(event), :class =>"btn btn-warning btn-sm fa fa-pencil"%>
                <%= link_to '', event, method: :delete, data: { confirm: 'Estas Seguro?' }, :class =>"btn btn-danger btn-sm fa fa-trash" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/events/new.html.erb
<h1><i class="fa fa-bullhorn"></i>
 Nuevo Evento
</h1>

<%= render 'form' %>

<%= link_to 'Volver', events_path, :class => "btn btn-default" %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
  <p>
    <strong>Nombre del Evento:</strong>
    <%= @event.name %>
  </p>
</div>

<div class="well">
  <%= link_to 'Editar', edit_event_path(@event), :class =>"btn btn-default" %> |
  <%= link_to 'Volver', events_path, :class =>"btn btn-default"  %>
</div>