config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'

  resources :events
  resources :categories
  resources :clientes

  root 'clientes#index'

  get 'orders' => 'orders#index'
  post 'orders/new/' => 'orders#new_orders'
  get  'orders/show/:id' => 'orders#show'
  get  'orders/all/' => 'orders#getallorders'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :details
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    @search = Category.search(params[:q])
    @categories = @search.result
    @categories = @categories.paginate(:per_page => 5, :page => params[:page])
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Nombre de la Categoria"%><br>
    <%= f.text_field :name,:class=> 'form-control' %>
  </div>
  <%= f.submit 'Guardar Categoria', :class => 'btn btn-success' %>
<% end %>

<br>

app/views/categories/edit.html.erb
<h1>
<i class="fa fa-diamond"></i>
Editar Categoria</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Ver', @category, :class=> 'btn btn-default' %> |
<%= link_to 'Volver', categories_path , :class=> 'btn btn-default'%>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1><i class="fa fa-diamond"></i>
 Categorias de Produtos
 <%= link_to 'Nueva Categoria', new_category_path, :class=> 'btn btn-default text-right' %> <br>
</h1>
<hr>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= search_form_for @search do |f| %>
      <div class="input-group">
        <%= f.text_field :name_cont, :class=>"form-control",:name=>"Search", :placeholder=>"Ingrese termino de busqueda y presione ENTER" %>
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    <% end %>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nombre de la Categoria</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td>
              <div class="btn-group">
                <%= link_to '', category , :class =>"btn btn-default btn-sm fa fa-eye" %>
                <%= link_to '', edit_category_path(category), :class =>"btn btn-warning btn-sm fa fa-pencil"%>
                <%= link_to '', category, method: :delete, data: { confirm: 'Estas Seguro?' }, :class =>"btn btn-danger btn-sm fa fa-trash" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
      <%= will_paginate @clientes, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>
  <i class="fa fa-diamond"></i>
  Nueva Categoria
</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Volver', categories_path, :class => "btn btn-default" %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
  <p>
    <strong>Nombre de la Categoria:</strong>
    <%= @category.name %>
  </p>
</div>

<div class="well">
  <%= link_to 'Editar', edit_category_path(@category), :class=>"btn btn-default" %> |
  <%= link_to 'Volver', categories_path, :class=>"btn btn-default" %>
</div>