config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'

  resources :events
  resources :categories
  resources :clientes

  root 'clientes#index'

  get 'orders' => 'orders#index'
  post 'orders/new/' => 'orders#new_orders'
  get  'orders/show/:id' => 'orders#show'
  get  'orders/all/' => 'orders#getallorders'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IQRS!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <div class="container">
    <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">IQRS</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <%= nav_link 'Dashboard', root_path %>
              <%= nav_link 'Ordenes de Trabajo', orders_path %>
              <%= nav_link 'Clientes', clientes_path %>
              <%= nav_link 'Reportes', "///" %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administración <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <%= nav_link 'Categorias de Productos', categories_path%>
                    <%= nav_link 'Eventos', events_path%>

                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="../navbar-fixed-top/">Alejandro Rodriguez Peña</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    <%= yield %>
  </div>

</body>
</html>